- name: "Install java"
  zypper:
    name: "{{ item }}"
    state: "{{ elastic_package_state }}"
    disable_gpg_check: yes
  with_items: "{{ elastic_packages }}"
  become: yes

- name: "create elk group"
  group:
    name: elastic
    state: present
  become: yes

- name: "create  elk user"
  user:
    name: elastic
    shell: /bin/bash
    group: elastic
  become: yes

- name: "create elastic home directory"
  file:
    path: "{{ elastic_home }}"
    owner: elastic
    group: elastic
    state: directory
  become: yes

- name: "create elastic data directory"
  file:
    path: "{{ elastic_datadir }}"
    owner: elastic
    group: elastic
    state: directory
  become: yes

- name: "Copy installation files"
  copy:
    src: elasticsearch
    dest: /opt
    owner: elastic
    group: elastic
  notify:
    - restart elasticsearch
  become: yes

- name: "Copy kibana installation rpm"
  copy:
    src: kibana-{{ elastic_version }}-x86_64.rpm
    dest: /opt
  become: yes

- name: "permission change of elastic"
  command: chmod -R 755 /opt/elasticsearch/bin
  become: yes

- name: "Install kibana rpm"
  zypper:
    name: /opt/kibana-{{ elastic_version }}-x86_64.rpm
    state: present
    disable_gpg_check: yes
  become: yes

- name: "create kibana log directory"
  file:
    path: /var/log/kibana
    owner: kibana
    group: kibana
    state: directory
  become: yes

- name: "change value for vm.swappiness "
  sysctl:
    name: vm.swappiness
    value: 1
    state: present
  become: yes

- name: "change  value for vm.max_map_count "
  sysctl:
    name: vm.max_map_count
    value: 362144
    state: present
  become: yes


- name: "change soft limit value -nofile"
  pam_limits:
    domain: elastic
    limit_type: soft
    limit_item: nofile
    value: 128000
  become: yes

- name: "change hard limit value -nofile"
  pam_limits:
    domain: elastic
    limit_type: hard
    limit_item: nofile
    value: 128000
  become: yes

- name: "Update elastic configuration"
  template:
    src: elasticsearch.yml.j2
    dest: /opt/elasticsearch/config/elasticsearch.yml
    owner: elastic
    group: elastic
  become: yes

- name: "Update elastic search jvm.options"
  template:
    src: jvm.options.j2
    dest: /opt/elasticsearch/config/jvm.options
    owner: elastic
    group: elastic
  become: yes

- name: "Update kibana configuration"
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: root
  notify:
    - restart kibana
  become: yes

- name: "Copy elastic service file"
  copy:
    src: elasticsearch.service
    dest: /usr/lib/systemd/system/elasticsearch.service
    owner: root
    group: root
    mode: 0755
  notify:
    - restart elasticsearch
  become: yes


- name: start elastic service
  systemd:
    state: started
    daemon_reload: yes
    name: elasticsearch
    enabled: yes
  become: yes

- name: start kibana service
  systemd:
    state: started
    daemon_reload: yes
    name: kibana
    enabled: yes
  become: yes
