- name: "Install java"
  zypper:
    name: "{{ item }}"
    state: "{{ logstash_package_state }}"
    disable_gpg_check: yes
  with_items: "{{ logstash_packages }}"
  become: yes


- name: "Copy logstash installation rpm"
  copy:
    src: logstash-{{ logstash_version }}.rpm
    dest: /tmp
  become: yes


- name: "Install logstash rpm"
  zypper:
    name: /tmp/logstash-{{ logstash_version }}.rpm
    state: present
    disable_gpg_check: yes
  become: yes


- name: "Update logstash jvm configuration"
  copy:
    src: jvm.options
    dest: /etc/logstash
    owner: root
    group: root
  notify:
    - restart logstash
  become: yes

- name: "Update logstash pipelines configuration"
  copy:
    src: pipelines.yml
    dest: /etc/logstash/
    owner: root
    group: root
  notify:
    - restart logstash
  become: yes

- name: "create pipeline  directory"
  file:
    path: /etc/logstash/pipeline_conf
    state: directory
  become: yes

- name: "Update logstash pipeline conf folder"
  copy:
    src: pipeline_conf
    dest: /etc/logstash/
    owner: root
    group: root
  notify:
    - restart logstash
  become: yes

- name: "Update logstash metric output file"
  template:
    src: output.conf.j2
    dest: /etc/logstash/pipeline_conf/metric/
    owner: root
    group: root
  notify:
    - restart logstash
  become: yes

- name: "create logstash queue directory"
  file:
    path: "{{ logstash_queue }}"
    owner: logstash
    group: logstash
    state: directory
  become: yes

- name: start logstash service
  systemd:
    state: started
    name: logstash
    enabled: yes
  become: yes
